#!/usr/bin/env bash
FILE="lxc-postinstall.sh"
if git diff --cached --name-only | grep -q "^${FILE}$"; then
    new=$(( $(git rev-list --count HEAD) + 1 ))
    sed -i "s/^REVISION=.*/REVISION=${new}/" "$FILE"
    git add "$FILE"
fi
